### ISSUE TITLE
MVP Playtesting

### ISSUE THREAD

**Issue by sindre0830** [NTNU-IMT3603-PLATFORMER/NTNU-IMT3606-GAME#72]
# Things I liked
* The pixel art is very good
* The main menu
* The music
* That the game runs in the browser
* Ingame UI
* Animations

# Things that could be improved
* Add settings to modify audio (ON/OFF, Slider for volume)
* Add points that can be collected during the game
* When jumping to the roof, the player gets stuck in one direction. Tried to jump to the roof and *slide* to the right, but was forced to the left.
![image](https://user-images.githubusercontent.com/30375850/140888292-f267ed64-54be-4a30-9a11-bbd8345410c5.png)

Very well done!

**Comment by Myteck** [comment]
Thanks for the feedback! We have now added volume controls, fixed the roof-problems and we've added rewards(points-ish) for killing enemies.
